// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// trie_create_from_airr
SEXP trie_create_from_airr(std::string data_path);
RcppExport SEXP _tcrtrieR_trie_create_from_airr(SEXP data_pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type data_path(data_pathSEXP);
    rcpp_result_gen = Rcpp::wrap(trie_create_from_airr(data_path));
    return rcpp_result_gen;
END_RCPP
}
// trie_create_from_strings
SEXP trie_create_from_strings(CharacterVector seqs, Nullable<CharacterVector> v_genes, Nullable<CharacterVector> j_genes);
RcppExport SEXP _tcrtrieR_trie_create_from_strings(SEXP seqsSEXP, SEXP v_genesSEXP, SEXP j_genesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type seqs(seqsSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type v_genes(v_genesSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type j_genes(j_genesSEXP);
    rcpp_result_gen = Rcpp::wrap(trie_create_from_strings(seqs, v_genes, j_genes));
    return rcpp_result_gen;
END_RCPP
}
// trie_load_subst_matrix
void trie_load_subst_matrix(SEXP xp, std::string matrix_path);
RcppExport SEXP _tcrtrieR_trie_load_subst_matrix(SEXP xpSEXP, SEXP matrix_pathSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< std::string >::type matrix_path(matrix_pathSEXP);
    trie_load_subst_matrix(xp, matrix_path);
    return R_NilValue;
END_RCPP
}
// trie_set_deletion_score
void trie_set_deletion_score(SEXP xp, double score);
RcppExport SEXP _tcrtrieR_trie_set_deletion_score(SEXP xpSEXP, SEXP scoreSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< double >::type score(scoreSEXP);
    trie_set_deletion_score(xp, score);
    return R_NilValue;
END_RCPP
}
// trie_set_max_query_length
void trie_set_max_query_length(SEXP xp, int n);
RcppExport SEXP _tcrtrieR_trie_set_max_query_length(SEXP xpSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    trie_set_max_query_length(xp, n);
    return R_NilValue;
END_RCPP
}
// trie_print_matrix
void trie_print_matrix(SEXP xp);
RcppExport SEXP _tcrtrieR_trie_print_matrix(SEXP xpSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    trie_print_matrix(xp);
    return R_NilValue;
END_RCPP
}
// trie_search
CharacterVector trie_search(SEXP xp, std::string query, int max_edits);
RcppExport SEXP _tcrtrieR_trie_search(SEXP xpSEXP, SEXP querySEXP, SEXP max_editsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< std::string >::type query(querySEXP);
    Rcpp::traits::input_parameter< int >::type max_edits(max_editsSEXP);
    rcpp_result_gen = Rcpp::wrap(trie_search(xp, query, max_edits));
    return rcpp_result_gen;
END_RCPP
}
// trie_search_any
bool trie_search_any(SEXP xp, std::string query, int max_edits);
RcppExport SEXP _tcrtrieR_trie_search_any(SEXP xpSEXP, SEXP querySEXP, SEXP max_editsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< std::string >::type query(querySEXP);
    Rcpp::traits::input_parameter< int >::type max_edits(max_editsSEXP);
    rcpp_result_gen = Rcpp::wrap(trie_search_any(xp, query, max_edits));
    return rcpp_result_gen;
END_RCPP
}
// trie_search_batch
List trie_search_batch(SEXP xp, CharacterVector queries, int max_edits);
RcppExport SEXP _tcrtrieR_trie_search_batch(SEXP xpSEXP, SEXP queriesSEXP, SEXP max_editsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type queries(queriesSEXP);
    Rcpp::traits::input_parameter< int >::type max_edits(max_editsSEXP);
    rcpp_result_gen = Rcpp::wrap(trie_search_batch(xp, queries, max_edits));
    return rcpp_result_gen;
END_RCPP
}
// trie_search_airr
DataFrame trie_search_airr(SEXP xp, std::string query, int max_sub, int max_ins, int max_del, Nullable<int> max_edits, Nullable<std::string> v_filter, Nullable<std::string> j_filter);
RcppExport SEXP _tcrtrieR_trie_search_airr(SEXP xpSEXP, SEXP querySEXP, SEXP max_subSEXP, SEXP max_insSEXP, SEXP max_delSEXP, SEXP max_editsSEXP, SEXP v_filterSEXP, SEXP j_filterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< std::string >::type query(querySEXP);
    Rcpp::traits::input_parameter< int >::type max_sub(max_subSEXP);
    Rcpp::traits::input_parameter< int >::type max_ins(max_insSEXP);
    Rcpp::traits::input_parameter< int >::type max_del(max_delSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type max_edits(max_editsSEXP);
    Rcpp::traits::input_parameter< Nullable<std::string> >::type v_filter(v_filterSEXP);
    Rcpp::traits::input_parameter< Nullable<std::string> >::type j_filter(j_filterSEXP);
    rcpp_result_gen = Rcpp::wrap(trie_search_airr(xp, query, max_sub, max_ins, max_del, max_edits, v_filter, j_filter));
    return rcpp_result_gen;
END_RCPP
}
// trie_search_matrix
DataFrame trie_search_matrix(SEXP xp, std::string query, double max_cost, Nullable<std::string> v_filter, Nullable<std::string> j_filter);
RcppExport SEXP _tcrtrieR_trie_search_matrix(SEXP xpSEXP, SEXP querySEXP, SEXP max_costSEXP, SEXP v_filterSEXP, SEXP j_filterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< std::string >::type query(querySEXP);
    Rcpp::traits::input_parameter< double >::type max_cost(max_costSEXP);
    Rcpp::traits::input_parameter< Nullable<std::string> >::type v_filter(v_filterSEXP);
    Rcpp::traits::input_parameter< Nullable<std::string> >::type j_filter(j_filterSEXP);
    rcpp_result_gen = Rcpp::wrap(trie_search_matrix(xp, query, max_cost, v_filter, j_filter));
    return rcpp_result_gen;
END_RCPP
}
// trie_search_for_all_airr
List trie_search_for_all_airr(SEXP xp, CharacterVector queries, int max_sub, int max_ins, int max_del, Nullable<int> max_edits, Nullable<std::string> v_filter, Nullable<std::string> j_filter);
RcppExport SEXP _tcrtrieR_trie_search_for_all_airr(SEXP xpSEXP, SEXP queriesSEXP, SEXP max_subSEXP, SEXP max_insSEXP, SEXP max_delSEXP, SEXP max_editsSEXP, SEXP v_filterSEXP, SEXP j_filterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type queries(queriesSEXP);
    Rcpp::traits::input_parameter< int >::type max_sub(max_subSEXP);
    Rcpp::traits::input_parameter< int >::type max_ins(max_insSEXP);
    Rcpp::traits::input_parameter< int >::type max_del(max_delSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type max_edits(max_editsSEXP);
    Rcpp::traits::input_parameter< Nullable<std::string> >::type v_filter(v_filterSEXP);
    Rcpp::traits::input_parameter< Nullable<std::string> >::type j_filter(j_filterSEXP);
    rcpp_result_gen = Rcpp::wrap(trie_search_for_all_airr(xp, queries, max_sub, max_ins, max_del, max_edits, v_filter, j_filter));
    return rcpp_result_gen;
END_RCPP
}
// trie_search_for_all_matrix
List trie_search_for_all_matrix(SEXP xp, CharacterVector queries, double max_cost, Nullable<std::string> v_filter, Nullable<std::string> j_filter);
RcppExport SEXP _tcrtrieR_trie_search_for_all_matrix(SEXP xpSEXP, SEXP queriesSEXP, SEXP max_costSEXP, SEXP v_filterSEXP, SEXP j_filterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type queries(queriesSEXP);
    Rcpp::traits::input_parameter< double >::type max_cost(max_costSEXP);
    Rcpp::traits::input_parameter< Nullable<std::string> >::type v_filter(v_filterSEXP);
    Rcpp::traits::input_parameter< Nullable<std::string> >::type j_filter(j_filterSEXP);
    rcpp_result_gen = Rcpp::wrap(trie_search_for_all_matrix(xp, queries, max_cost, v_filter, j_filter));
    return rcpp_result_gen;
END_RCPP
}
// trie_cluster_usage
DataFrame trie_cluster_usage(SEXP xp, CharacterVector cluster, int max_sub, int max_ins, int max_del, Nullable<int> max_edits, Nullable<std::string> v_filter, Nullable<std::string> j_filter);
RcppExport SEXP _tcrtrieR_trie_cluster_usage(SEXP xpSEXP, SEXP clusterSEXP, SEXP max_subSEXP, SEXP max_insSEXP, SEXP max_delSEXP, SEXP max_editsSEXP, SEXP v_filterSEXP, SEXP j_filterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type cluster(clusterSEXP);
    Rcpp::traits::input_parameter< int >::type max_sub(max_subSEXP);
    Rcpp::traits::input_parameter< int >::type max_ins(max_insSEXP);
    Rcpp::traits::input_parameter< int >::type max_del(max_delSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type max_edits(max_editsSEXP);
    Rcpp::traits::input_parameter< Nullable<std::string> >::type v_filter(v_filterSEXP);
    Rcpp::traits::input_parameter< Nullable<std::string> >::type j_filter(j_filterSEXP);
    rcpp_result_gen = Rcpp::wrap(trie_cluster_usage(xp, cluster, max_sub, max_ins, max_del, max_edits, v_filter, j_filter));
    return rcpp_result_gen;
END_RCPP
}
// trie_cluster_usage_matrix
DataFrame trie_cluster_usage_matrix(SEXP xp, CharacterVector cluster, double max_cost, Nullable<std::string> v_filter, Nullable<std::string> j_filter);
RcppExport SEXP _tcrtrieR_trie_cluster_usage_matrix(SEXP xpSEXP, SEXP clusterSEXP, SEXP max_costSEXP, SEXP v_filterSEXP, SEXP j_filterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type cluster(clusterSEXP);
    Rcpp::traits::input_parameter< double >::type max_cost(max_costSEXP);
    Rcpp::traits::input_parameter< Nullable<std::string> >::type v_filter(v_filterSEXP);
    Rcpp::traits::input_parameter< Nullable<std::string> >::type j_filter(j_filterSEXP);
    rcpp_result_gen = Rcpp::wrap(trie_cluster_usage_matrix(xp, cluster, max_cost, v_filter, j_filter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tcrtrieR_trie_create_from_airr", (DL_FUNC) &_tcrtrieR_trie_create_from_airr, 1},
    {"_tcrtrieR_trie_create_from_strings", (DL_FUNC) &_tcrtrieR_trie_create_from_strings, 3},
    {"_tcrtrieR_trie_load_subst_matrix", (DL_FUNC) &_tcrtrieR_trie_load_subst_matrix, 2},
    {"_tcrtrieR_trie_set_deletion_score", (DL_FUNC) &_tcrtrieR_trie_set_deletion_score, 2},
    {"_tcrtrieR_trie_set_max_query_length", (DL_FUNC) &_tcrtrieR_trie_set_max_query_length, 2},
    {"_tcrtrieR_trie_print_matrix", (DL_FUNC) &_tcrtrieR_trie_print_matrix, 1},
    {"_tcrtrieR_trie_search", (DL_FUNC) &_tcrtrieR_trie_search, 3},
    {"_tcrtrieR_trie_search_any", (DL_FUNC) &_tcrtrieR_trie_search_any, 3},
    {"_tcrtrieR_trie_search_batch", (DL_FUNC) &_tcrtrieR_trie_search_batch, 3},
    {"_tcrtrieR_trie_search_airr", (DL_FUNC) &_tcrtrieR_trie_search_airr, 8},
    {"_tcrtrieR_trie_search_matrix", (DL_FUNC) &_tcrtrieR_trie_search_matrix, 5},
    {"_tcrtrieR_trie_search_for_all_airr", (DL_FUNC) &_tcrtrieR_trie_search_for_all_airr, 8},
    {"_tcrtrieR_trie_search_for_all_matrix", (DL_FUNC) &_tcrtrieR_trie_search_for_all_matrix, 5},
    {"_tcrtrieR_trie_cluster_usage", (DL_FUNC) &_tcrtrieR_trie_cluster_usage, 8},
    {"_tcrtrieR_trie_cluster_usage_matrix", (DL_FUNC) &_tcrtrieR_trie_cluster_usage_matrix, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_tcrtrieR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
