# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

trie_create_from_airr <- function(data_path) {
    .Call(`_tcrtrieR_trie_create_from_airr`, data_path)
}

trie_create_from_strings <- function(seqs, v_genes = NULL, j_genes = NULL) {
    .Call(`_tcrtrieR_trie_create_from_strings`, seqs, v_genes, j_genes)
}

trie_load_subst_matrix <- function(xp, matrix_path) {
    invisible(.Call(`_tcrtrieR_trie_load_subst_matrix`, xp, matrix_path))
}

trie_set_deletion_score <- function(xp, score) {
    invisible(.Call(`_tcrtrieR_trie_set_deletion_score`, xp, score))
}

trie_set_max_query_length <- function(xp, n) {
    invisible(.Call(`_tcrtrieR_trie_set_max_query_length`, xp, n))
}

trie_print_matrix <- function(xp) {
    invisible(.Call(`_tcrtrieR_trie_print_matrix`, xp))
}

trie_search <- function(xp, query, max_edits) {
    .Call(`_tcrtrieR_trie_search`, xp, query, max_edits)
}

trie_search_any <- function(xp, query, max_edits) {
    .Call(`_tcrtrieR_trie_search_any`, xp, query, max_edits)
}

trie_search_batch <- function(xp, queries, max_edits) {
    .Call(`_tcrtrieR_trie_search_batch`, xp, queries, max_edits)
}

trie_search_airr <- function(xp, query, max_sub, max_ins, max_del, max_edits = NULL, v_filter = NULL, j_filter = NULL) {
    .Call(`_tcrtrieR_trie_search_airr`, xp, query, max_sub, max_ins, max_del, max_edits, v_filter, j_filter)
}

trie_search_matrix <- function(xp, query, max_cost, v_filter = NULL, j_filter = NULL) {
    .Call(`_tcrtrieR_trie_search_matrix`, xp, query, max_cost, v_filter, j_filter)
}

trie_search_for_all_airr <- function(xp, queries, max_sub, max_ins, max_del, max_edits = NULL, v_filter = NULL, j_filter = NULL) {
    .Call(`_tcrtrieR_trie_search_for_all_airr`, xp, queries, max_sub, max_ins, max_del, max_edits, v_filter, j_filter)
}

trie_search_for_all_matrix <- function(xp, queries, max_cost, v_filter = NULL, j_filter = NULL) {
    .Call(`_tcrtrieR_trie_search_for_all_matrix`, xp, queries, max_cost, v_filter, j_filter)
}

trie_cluster_usage <- function(xp, cluster, max_sub, max_ins, max_del, max_edits = NULL, v_filter = NULL, j_filter = NULL) {
    .Call(`_tcrtrieR_trie_cluster_usage`, xp, cluster, max_sub, max_ins, max_del, max_edits, v_filter, j_filter)
}

trie_cluster_usage_matrix <- function(xp, cluster, max_cost, v_filter = NULL, j_filter = NULL) {
    .Call(`_tcrtrieR_trie_cluster_usage_matrix`, xp, cluster, max_cost, v_filter, j_filter)
}

